on: 
  push:
    branches:
      - main
      - 'dev/*' # Escucha push en cualquier rama que comience con 'dev/'

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files to admin
      # Condición para ejecutar solo en main y solo después del merge
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
        username: ${{ secrets.GIT_CPANEL_REACT_USER }}
        password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
        protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
        local-dir: ./dist/
        server-dir: ./admin/

    - name: 📂 Sync files to pruebas
      # Condición para ejecutar solo en ramas diferentes a main
      if: github.ref != 'refs/heads/main'
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
        username: ${{ secrets.GIT_CPANEL_REACT_USER }}
        password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
        protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
        local-dir: ./dist/
        server-dir: ./pruebas/admin/